### PR TITLE
change owlgen to use default_prefix for namespace

### LINKED ISSUE #163: owlgen uses namespaces incorrectly
everything is placed into the meta namespace

### PR DESCRIPTION
**Pull request by cmungall**
Fixes bug where owlgen placed all classes, properties into meta namespace.
The fix incvolves changing how definition_uri is populated while schema loading.
Fixes #163
﻿

### CODE REVIEW

**Comment by hsolbrig** [comment]
A couple of questions / problems with this fix:

1) The separator between the base URI and item has been changed from '/' to '#'.  This breaks some existing code -- we need to discuss why and whether there might be a gentler way to do it.
2) There is a problem with aliases in the owl generator.  See: [tests/test_issues/input/issue_163c.yaml]() for details.  We need to discuss approaches

**Comment by cmungall** [comment]
hmm I don't recall intending to change anything from / to #...

**Comment by hsolbrig** [comment]
@cmungall  - see https://github.com/biolink/biolinkml/blob/issue-163-redux/biolinkml/utils/mergeutils.py#L70

**Comment by cmungall** [comment]
OK, changed '#' to '/' (this is only the case where a prefix is not declared)

Looks like I now have conflicts, most of these seem to be generated test files, maybe I shouldn't have included in the PR

**Comment by hsolbrig** [comment]
We'll catch the conflicts -- @jiaola is going to create a merge action that automatically rewrites them.  Thanks!

**Pull request merged**
